### PR TITLE
new free ML learning link added

### PR DESCRIPTION
**Pull request by thedevshubham**
new free ML learning link added

### CODE REVIEW

**Review by meinhoonharsh — APPROVED** [review]
Thanks for the Contribution

**Comment by thedevshubham** [comment]
> Thanks for the Contribution

@meinhoonharsh Thanks, you have submitted my MR, but it is still showing Pull request not merged yet in my Hacktoberfest dashboard, any idea ?

**Comment by meinhoonharsh** [comment]
It sometimes takes time to reflect on their site. If it didn't get updated by evening, then let us know

**Comment by thedevshubham** [comment]
> It sometimes takes time to reflect on their site. If it didn't get updated by evening, then let us know

Thanks! I will do the same

**Pull request merged**
